### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by funafuna46** [funafuna46/gift_app#42]
issueを作成いたしました。
ご確認の程、どうぞよろしくお願いいたします。

### 実装予定の機能（MVP時点）
- [ ] 会員登録機能
- [ ] LINEログイン機能
- [ ] ギフト券一覧機能（未ログインユーザーも閲覧可能）
  - テンプレートギフト券
  - オリジナルギフト券
- [ ] ギフト券作成機能（テンプレートギフト券、オリジナルギフト券）
  - 作成したギフト券は一覧への公開・非公開を選択可能
  - 有効期限の設定も可能
- [ ] ギフト券共有機能
- [ ] ギフト券検索機能（ギフト内容、送信先カテゴリ）
- [ ] ギフト券お気に入り機能
- [ ] マイページ
  - 貰ったギフト券一覧機能
  - 贈ったギフト券一覧機能
  - お気に入りギフト券一覧機能
  - ギフト券詳細閲覧機能
  - プロフィール編集機能
- [ ] X（旧Twitter）シェア機能
  - ギフト券を受け取ったユーザーが貰って嬉しかったギフト券をXでシェア可能

### 必要なページ
- [ ] トップページ
- [ ] ギフト券選択画面
- [ ] テンプレートギフト券選択画面
- [ ] オリジナルギフト券作成画面
- [ ] ギフト券送信完了画面
- [ ] ギフト券一覧画面
- [ ] 未ログインユーザー用ギフト券一覧画面
- [ ] マイページ
- [ ] プロフィール編集画面
- [ ] ギフト券詳細画面

**Comment by takyyi** [comment]
LGTMです！

**Comment by funafuna46** [comment]
ご確認いただき、ありがとうございます！
