### ISSUE TITLE
MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by funafuna46** [funafuna46/gift_app#91]
お世話になっております。
MVPリリースのレビュー依頼を提出いたします。

READMEレビュー時から変更した機能につきましては、
2/22の開発スケジュール見積もり面談にて、富田講師と確認済です。

ご確認のほど、どうぞよろしくお願いいたします。

## 各種情報
サービス名　Thankyoupon
サービスURL　https://gift-app46-4c2b67d1ab7f.herokuapp.com/

### テンプレートクーポン券
- [x] 既に用意してあるデザインを選択、共有機能

### オリジナルクーポン券
- [x] 一覧機能  ~~（未ログインユーザーも閲覧可能）~~
- [x] 作成機能
  - [x] 一覧への公開・非公開を選択可能
  - [x] 有効期限の設定も可能
- [x] 共有機能
- [x] 検索機能（ギフト内容、送信先カテゴリ）
- [x] お気に入り機能

### マイページ
  - [ ] 貰ったクーポン券一覧機能→本リリースにて実装
  - [ ] 贈ったクーポン券一覧機能→本リリースにて実装
  - [x] お気に入りクーポン券一覧機能
  - [x] クーポン券詳細閲覧機能
 
### その他 
- [x] LINEログイン機能（会員登録機能）
- [x] プロフィール編集機能
- [ ] X（旧Twitter）シェア機能→本リリースにて実装

### 追加した機能
- [x] クーポン券編集、削除機能
- [x] マイページ内、作成したクーポン券一覧機能
### 本リリースで実装する機能
 - [ ] 貰ったクーポン券一覧機能
 - [ ] 贈ったクーポン券一覧機能
 - [ ] X（旧Twitter）シェア機能

## サービスイメージがわかるようなスクリーンショット等
トップページ
![image](https://github.com/funafuna46/gift_app/assets/136342662/78719b47-f799-48c6-af89-849f81159103)

テンプレートクーポン券選択画面
![image](https://github.com/funafuna46/gift_app/assets/136342662/3dbe05e7-bced-44f1-999e-9012b6d7f5b1)

オリジナルクーポン券作成画面
![image](https://github.com/funafuna46/gift_app/assets/136342662/705d79fd-14ae-44cf-9e35-115ffb8d659a)

マイページ
![image](https://github.com/funafuna46/gift_app/assets/136342662/19ed48e3-6378-44db-a855-df733ecbf23f)

**Comment by tmtkzk0823** [comment]
確認しました！
しっかり実装できているかと思います！

LGTMです！

**Comment by funafuna46** [comment]
ご確認いただき、ありがとうございます！
